[project]
name = "project_name"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "5.4.0"

[tasks]

[dependencies]
pandas = ">=2.2.2,<2.3"
polars = ">=1.2.1,<1.3"
pyarrow = ">=17.0.0,<17.1"
