[project]
name = "convert_website"
version = "0.1.0"
description = "Convert Wordpress website to static website"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "5.4.0"

[tasks]
step01 = { cmd = "python src/s01.py", inputs = ['input/localhost.sql.gz'], outputs = ['output/s01_posts.parquet']}
step02 = { cmd = "python src/s02.py", depends-on = ["step01"], inputs = ['output/s01_posts.parquet'], outputs = ['output/s02_website_read_posts.parquet'] }
step03 = { cmd = "python src/s03.py", depends-on = ["step02"], inputs = ['input/01posts.txt', 'output/s02_website_read_posts.parquet'], outputs = ['output/s03_website_textfile_merged.parquet'] }
step04 = { cmd = "python src/s04.py", depends-on = ["step03"], inputs = ['output/s03_website_textfile_merged.parquet'], outputs = ['output/md_posts/*'] }

[dependencies]
pandas = ">=2.2.2,<2.3"
polars = ">=1.2.1,<1.3"
pyarrow = ">=17.0.0,<17.1"
bs4 = ">=4.12.3,<4.13"
validators = ">=0.33.0,<0.34"
